files:
  - name: bad_sheep.txt
    written: "2024-06-04"
    updated: "2024-06-04"

  - name: crutch.txt
    written: "2025-06-04"
    updated: "2025-06-04"

  - name: emergence.txt
    written: "2023-08-31"
    updated: "2024-02-27"

  - name: highway_trash.txt
    written: "2023-08-31"
    updated: "2024-02-23"

  - name: only_the_wind.txt
    written: "2025-07-16"
    updated: "2025-07-16"

  - name: play_monster.txt
    written: "2025-03-08"
    updated: "2025-03-08"

  - name: thursday.txt
    written: "2023-08-31"
    updated: "2024-02-23"

  - name: weakness.txt
    written: "2022-06-03"
    updated: "2023-10-15"

